In [104]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from dotenv import load_dotenv
import janitor
import os
from pathlib import Path
import openpyxl
import sqlalchemy as sa

# Desactivar notación científica
pd.set_option('display.float_format', lambda x: '%.3f' % x)
np.set_printoptions(suppress=True)

# Cargar variables de entorno
load_dotenv()

print("✅ Librerías importadas correctamente")

✅ Librerías importadas correctamente

In [105]:
df = pd.read_pickle('../02_datos/03_Entrenamiento/train.pkl')
df

,state_id,store_id,dept_id,cat_id,item_id,wm_yr_wk,d,ventas,sell_price,year,month,wday,weekday,event_name_1,event_type_1,event_name_2,event_type_2
date,,,,,,,,,,,,,,,,,
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_090,11249,d_704,0,1.250,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_120,11249,d_704,0,4.980,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_202,11249,d_704,20,4.280,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_252,11249,d_704,34,1.480,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_288,11249,d_704,0,NaN,2013,1,4,Tuesday,NewYear,National,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-11-30,CA,CA_4,FOODS_3,FOODS,FOODS_3_329,11544,d_1767,5,2.980,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA,CA_4,FOODS_3,FOODS,FOODS_3_555,11544,d_1767,4,1.680,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA,CA_4,FOODS_3,FOODS,FOODS_3_586,11544,d_1767,9,1.680,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA,CA_4,FOODS_3,FOODS,FOODS_3_587,11544,d_1767,13,2.480,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA,CA_4,FOODS_3,FOODS,FOODS_3_714,11544,d_1767,9,1.580,2015,11,3,Monday,NaN,NaN,NaN,NaN

In [106]:
df.info()

<class 'pandas.DataFrame'>
Index: 21280 entries, 2013-01-01 to 2015-11-30
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state_id      21280 non-null  str
 1   store_id      21280 non-null  str
 2   dept_id       21280 non-null  str
 3   cat_id        21280 non-null  str
 4   item_id       21280 non-null  str
 5   wm_yr_wk      21280 non-null  int64
 6   d             21280 non-null  str
 7   ventas        21280 non-null  int64
 8   sell_price    21209 non-null  float64
 9   year          21280 non-null  int64
 10  month         21280 non-null  int64
 11  wday          21280 non-null  int64
 12  weekday       21280 non-null  str
 13  event_name_1  1700 non-null   str
 14  event_type_1  1700 non-null   str
 15  event_name_2  60 non-null     str
 16  event_type_2  60 non-null     str
dtypes: float64(1), int64(5), str(11)
memory usage: 4.0 MB

In [107]:
df = df.astype({'year': 'O',
                'month': 'O',
                'wday': 'O'
               })

df.info()

<class 'pandas.DataFrame'>
Index: 21280 entries, 2013-01-01 to 2015-11-30
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state_id      21280 non-null  str
 1   store_id      21280 non-null  str
 2   dept_id       21280 non-null  str
 3   cat_id        21280 non-null  str
 4   item_id       21280 non-null  str
 5   wm_yr_wk      21280 non-null  int64
 6   d             21280 non-null  str
 7   ventas        21280 non-null  int64
 8   sell_price    21209 non-null  float64
 9   year          21280 non-null  object
 10  month         21280 non-null  object
 11  wday          21280 non-null  object
 12  weekday       21280 non-null  str
 13  event_name_1  1700 non-null   str
 14  event_type_1  1700 non-null   str
 15  event_name_2  60 non-null     str
 16  event_type_2  60 non-null     str
dtypes: float64(1), int64(2), object(3), str(11)
memory usage: 4.0+ MB

In [108]:
df.nunique().sort_values()

state_id           1
dept_id            1
cat_id             1
store_id           2
event_type_2       2
event_name_2       3
year               3
event_type_1       4
weekday            7
wday               7
item_id           10
month             12
sell_price        23
event_name_1      30
wm_yr_wk         153
ventas           301
d               1064
dtype: int64

In [109]:
df.drop(columns=['state_id', 'dept_id', 'cat_id' ], inplace=True)

In [110]:
df.duplicated().sum()

np.int64(0)

In [111]:
cat = df.select_dtypes(exclude='number').copy()

In [112]:
num = df.select_dtypes(include='number').copy()

In [113]:
cat

,store_id,item_id,d,year,month,wday,weekday,event_name_1,event_type_1,event_name_2,event_type_2
date,,,,,,,,,,,
2013-01-01,CA_3,FOODS_3_090,d_704,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA_3,FOODS_3_120,d_704,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA_3,FOODS_3_202,d_704,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA_3,FOODS_3_252,d_704,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA_3,FOODS_3_288,d_704,2013,1,4,Tuesday,NewYear,National,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2015-11-30,CA_4,FOODS_3_329,d_1767,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA_4,FOODS_3_555,d_1767,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA_4,FOODS_3_586,d_1767,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA_4,FOODS_3_587,d_1767,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA_4,FOODS_3_714,d_1767,2015,11,3,Monday,NaN,NaN,NaN,NaN

In [114]:
cat.isna().sum().sort_values(ascending=False)

event_name_2    21220
event_type_2    21220
event_name_1    19580
event_type_1    19580
d                   0
store_id            0
item_id             0
weekday             0
wday                0
month               0
year                0
dtype: int64

In [115]:
cat.event_name_1.value_counts(dropna=False)

event_name_1
NaN                    19580
NewYear                   60
OrthodoxChristmas         60
MartinLutherKingDay       60
SuperBowl                 60
LentStart                 60
ValentinesDay             60
PresidentsDay             60
LentWeek2                 60
Purim End                 60
StPatricksDay             60
Easter                    60
Pesach End                60
Mother's day              60
MemorialDay               60
NBAFinalsStart            60
NBAFinalsEnd              60
IndependenceDay           60
Ramadan starts            60
Eid al-Fitr               60
LaborDay                  60
ColumbusDay               60
EidAlAdha                 60
Halloween                 60
VeteransDay               60
Thanksgiving              60
OrthodoxEaster            40
Father's day              40
Chanukah End              40
Christmas                 40
Cinco De Mayo             40
Name: count, dtype: int64

In [116]:
cat.event_type_2.value_counts(dropna=False)

event_type_2
NaN          21220
Cultural        40
Religious       20
Name: count, dtype: int64

In [117]:
cat = cat.reset_index(drop=True)
pd.crosstab(cat.event_name_1,[cat.event_type_2, cat.event_name_2])

event_type_2        Cultural                   Religious
event_name_2   Cinco De Mayo Father's day OrthodoxEaster
event_name_1
Easter                     0            0             20
NBAFinalsEnd               0           20              0
OrthodoxEaster            20            0              0

In [118]:
columns_eliminar = ['event_type_2', 'event_name_2']
cat.drop(columns=columns_eliminar, inplace=True)

In [155]:
cat['event_name_1'] = cat['event_name_1'].fillna('Sin evento')
cat['event_type_1'] = cat['event_type_1'].fillna('Sin evento')

In [156]:
cat.nunique().sort_values()

store_id           2
year               3
event_type_1       5
weekday            7
wday               7
item_id           10
month             12
event_name_1      31
d               1064
dtype: int64

In [157]:
for variable in cat:
    print(variable + '\n')
    print(cat[variable].value_counts(dropna=False))
    print('\n')

store_id

store_id
CA_3    10640
CA_4    10640
Name: count, dtype: int64


item_id

item_id
FOODS_3_090    2128
FOODS_3_120    2128
FOODS_3_202    2128
FOODS_3_252    2128
FOODS_3_288    2128
FOODS_3_329    2128
FOODS_3_555    2128
FOODS_3_586    2128
FOODS_3_587    2128
FOODS_3_714    2128
Name: count, dtype: int64


d

d
d_704     20
d_705     20
d_706     20
d_707     20
d_708     20
          ..
d_1763    20
d_1764    20
d_1765    20
d_1766    20
d_1767    20
Name: count, Length: 1064, dtype: int64


year

year
2013    7300
2014    7300
2015    6680
Name: count, dtype: int64


month

month
1     1860
3     1860
5     1860
7     1860
8     1860
10    1860
4     1800
6     1800
9     1800
11    1800
2     1680
12    1240
Name: count, dtype: int64


wday

wday
4    3040
5    3040
6    3040
7    3040
1    3040
2    3040
3    3040
Name: count, dtype: int64


weekday

weekday
Tuesday      3040
Wednesday    3040
Thursday     3040
Friday       3040
Saturday     3040
Sunday       3040
Monday       3040
Name: count, dtype: int64


event_name_1

event_name_1
Sin evento             19580
NewYear                   60
OrthodoxChristmas         60
MartinLutherKingDay       60
SuperBowl                 60
LentStart                 60
ValentinesDay             60
PresidentsDay             60
LentWeek2                 60
Purim End                 60
StPatricksDay             60
Easter                    60
Pesach End                60
Mother's day              60
MemorialDay               60
NBAFinalsStart            60
NBAFinalsEnd              60
IndependenceDay           60
Ramadan starts            60
Eid al-Fitr               60
LaborDay                  60
ColumbusDay               60
EidAlAdha                 60
Halloween                 60
VeteransDay               60
Thanksgiving              60
OrthodoxEaster            40
Father's day              40
Chanukah End              40
Christmas                 40
Cinco De Mayo             40
Name: count, dtype: int64


event_type_1

event_type_1
Sin evento    19580
National        580
Religious       560
Cultural        380
Sporting        180
Name: count, dtype: int64

In [159]:
df.groupby('year').d.nunique()

year
2013    365
2014    365
2015    334
Name: d, dtype: int64