In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from dotenv import load_dotenv
import janitor
import os
from pathlib import Path
import openpyxl
import sqlalchemy as sa

# Desactivar notación científica
pd.set_option('display.float_format', lambda x: '%.3f' % x)
np.set_printoptions(suppress=True)

# Cargar variables de entorno
load_dotenv()

print("✅ Librerías importadas correctamente")

✅ Librerías importadas correctamente

In [2]:
df = pd.read_pickle('../02_datos/03_Entrenamiento/train.pkl')
df

,state_id,store_id,dept_id,cat_id,item_id,wm_yr_wk,d,ventas,sell_price,year,month,wday,weekday,event_name_1,event_type_1,event_name_2,event_type_2
date,,,,,,,,,,,,,,,,,
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_090,11249,d_704,0,1.250,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_120,11249,d_704,0,4.980,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_202,11249,d_704,20,4.280,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_252,11249,d_704,34,1.480,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_288,11249,d_704,0,NaN,2013,1,4,Tuesday,NewYear,National,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-11-30,CA,CA_4,FOODS_3,FOODS,FOODS_3_329,11544,d_1767,5,2.980,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA,CA_4,FOODS_3,FOODS,FOODS_3_555,11544,d_1767,4,1.680,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA,CA_4,FOODS_3,FOODS,FOODS_3_586,11544,d_1767,9,1.680,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA,CA_4,FOODS_3,FOODS,FOODS_3_587,11544,d_1767,13,2.480,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA,CA_4,FOODS_3,FOODS,FOODS_3_714,11544,d_1767,9,1.580,2015,11,3,Monday,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
Index: 21280 entries, 2013-01-01 to 2015-11-30
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state_id      21280 non-null  str
 1   store_id      21280 non-null  str
 2   dept_id       21280 non-null  str
 3   cat_id        21280 non-null  str
 4   item_id       21280 non-null  str
 5   wm_yr_wk      21280 non-null  int64
 6   d             21280 non-null  str
 7   ventas        21280 non-null  int64
 8   sell_price    21209 non-null  float64
 9   year          21280 non-null  int64
 10  month         21280 non-null  int64
 11  wday          21280 non-null  int64
 12  weekday       21280 non-null  str
 13  event_name_1  1700 non-null   str
 14  event_type_1  1700 non-null   str
 15  event_name_2  60 non-null     str
 16  event_type_2  60 non-null     str
dtypes: float64(1), int64(5), str(11)
memory usage: 4.0 MB

In [8]:
df = df.astype({'year': 'O',
                'month': 'O',
                'wday': 'O'
               })

df.info()

<class 'pandas.DataFrame'>
Index: 21280 entries, 2013-01-01 to 2015-11-30
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state_id      21280 non-null  str
 1   store_id      21280 non-null  str
 2   dept_id       21280 non-null  str
 3   cat_id        21280 non-null  str
 4   item_id       21280 non-null  str
 5   wm_yr_wk      21280 non-null  int64
 6   d             21280 non-null  str
 7   ventas        21280 non-null  int64
 8   sell_price    21209 non-null  float64
 9   year          21280 non-null  object
 10  month         21280 non-null  object
 11  wday          21280 non-null  object
 12  weekday       21280 non-null  str
 13  event_name_1  1700 non-null   str
 14  event_type_1  1700 non-null   str
 15  event_name_2  60 non-null     str
 16  event_type_2  60 non-null     str
dtypes: float64(1), int64(2), object(3), str(11)
memory usage: 4.5+ MB

In [12]:
df.nunique().sort_values()

state_id           1
dept_id            1
cat_id             1
store_id           2
event_type_2       2
event_name_2       3
year               3
event_type_1       4
weekday            7
wday               7
item_id           10
month             12
sell_price        23
event_name_1      30
wm_yr_wk         153
ventas           301
d               1064
dtype: int64

In [13]:
df.drop(columns=['state_id', 'dept_id', 'cat_id' ], inplace=True)

In [15]:
df.duplicated().sum()

np.int64(0)

In [22]:
cat = df.select_dtypes(exclude='number').copy()

In [17]:
num = df.select_dtypes(include='number').copy()

In [26]:
cat

,store_id,item_id,d,year,month,wday,weekday,event_name_1,event_type_1,event_name_2,event_type_2
date,,,,,,,,,,,
2013-01-01,CA_3,FOODS_3_090,d_704,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA_3,FOODS_3_120,d_704,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA_3,FOODS_3_202,d_704,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA_3,FOODS_3_252,d_704,2013,1,4,Tuesday,NewYear,National,NaN,NaN
2013-01-01,CA_3,FOODS_3_288,d_704,2013,1,4,Tuesday,NewYear,National,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2015-11-30,CA_4,FOODS_3_329,d_1767,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA_4,FOODS_3_555,d_1767,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA_4,FOODS_3_586,d_1767,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA_4,FOODS_3_587,d_1767,2015,11,3,Monday,NaN,NaN,NaN,NaN
2015-11-30,CA_4,FOODS_3_714,d_1767,2015,11,3,Monday,NaN,NaN,NaN,NaN